version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-flavorstar-workflows
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            npm test
  deploy:
    working_directory: ~/circleci-flavorstar-workflows
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run: # deploy to CDN
          name: 'Deploy to S3'
          command: |
            aws s3 sync build/ s3://johndrew-flavor-star
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master